### ISSUE TITLE
How max refraction affects internal reflection?

### ISSUE THREAD

**Issue by ghost** [ChaosGroup/vraymtl_glsl#1]
any tips on reproducing the max depth option in VRayMtl?
couldn't find it here

**Comment by chazbg** [comment]
Hi Iyad,

This implementation doesn't support multiple ray bounces because adding such support would require knowledge of the whole scene. That's why there isn't a max depth option here.

If you want to implement multiple refraction bounces in your application you can use `sampleRefractBRDF` to generate refraction directions and then you would need to intersect them with the objects in the scene (this part requires the knowledge of the whole scene that we don't have here).

Hope that helps,
Dian

**Comment by ghost** [comment]
Many thanks for insights 🙏, will look into the code you mentioned 

Best regards,
Iyad
