### ISSUE TITLE
I wonder if the function computeDirectDiffuseContribution should be divided by π at the end

### ISSUE THREAD

**Issue by wzaqrh** [ChaosGroup/vraymtl_glsl#5]
vec3 vrayMtlDiffuse(vec3 lightDir, vec3 normal) {
	return vec3(max(0.0, dot(lightDir, normal)));
}
vec3 computeDirectDiffuseContribution(VRayMtlInitParams params, VRayMtlContext ctx, vec3 lightDir) {
	vec3 res = vec3(0.0);
	if (params.roughness < 1e-6) {
		res = vrayMtlDiffuse(lightDir, ctx.geomNormal);
	} else {
		res = vrayMtlDiffuseRoughness(lightDir, ctx);
	}

	if (ctx.hasSheen) {
		vec3 sheenLightDim = getSheenAlbedoLightDim(params.sheenColor, dot(lightDir, ctx.geomNormal), ctx.sheenGloss);
		res *= sheenLightDim;
	}

	return res;
}
i cannot find a π division at this function, according to formula, should res to divided by π at the end?

**Comment by wzaqrh** [comment]
or the π division was happend any where else? i am just learning from your zmazing code at beginning.

**Comment by dian-nikolov-chaos** [comment]
You are right that the Lambert diffuse BRDF contains a division by pi:
`f(in, out) = R / pi` (https://www.pbr-book.org/3ed-2018/Reflection_Models/Lambertian_Reflection)

However, this estimates the reflected light only for a single set of incoming and outgoing directions.
In order to compute the full lighting we need to need to compute an integral over the whole hemisphere of directions:
`F(out) = I_Omega f(in, out) * L_i * cos(theta_in) d_omega_in` (https://people.cs.kuleuven.be/~philip.dutre/GI/TotalCompendium.pdf#page=17, the first 2 integrals in (30), https://en.wikipedia.org/wiki/Rendering_equation)

In this shader, the direct lighting comes from a single direction and is zero elsewhere `vec3 lightDir = normalize(vec3(1, 1, 0.2));`.
Because of this, the pi division cancels with the pi multiplication from the integration:
https://seblagarde.wordpress.com/2012/01/08/pi-or-not-to-pi-in-game-lighting-equation/
https://renderwonk.com/publications/s2010-shading-course/hoffman/s2010_physically_based_shading_hoffman_a_notes.pdf#page=22

**Comment by wzaqrh** [comment]
that's it, thank you for the detailed informations
